### ISSUE TITLE
[Feat] Printing an Image on Terminal

### ISSUE THREAD

**Issue by leehe228** [amo33/CLICV#3]
## 🛠 Issue

Printing a static image on Terminal

## 📝 To-do

- [ ] Get terminal size
- [ ] Read an image file from arguments 
- [ ] Printing a static image
